theme = "onedark"

[editor]
mouse = true
auto-save = true
true-color = true
cursorline = true
color-modes = true
rulers = [80, 100]
bufferline = "always"
soft-wrap.enable = true
line-number = "relative"
middle-click-paste = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "│"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "diagnostics", "file-name"]
right = ["position-percentage", "spacer", "position"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.normal]
# For Kakoune like config
S-left = "extend_char_left"
S-right = "extend_char_right"
S-up = "extend_line_up"
S-down = "extend_line_down"

"#" = "toggle_comments"
C-c = "no_op"
q = { q = "wclose" }
"space" = { "space" = "keep_primary_selection",  "q" = ":buffer-close" }
"esc" = [ "normal_mode", ":format" , ":write" ] # For quick saving

A-o = "add_newline_below"
A-O = [ "open_above", "normal_mode" ] # Doesn't work.

# Windows-like movement
C-left = [ "move_prev_word_start", "move_char_left", "move_char_right" ]
C-right = [ "move_next_word_start", "move_char_left", "move_char_right" ]

"ret" = ":write"
"C-q" = ":quit!"

[keys.insert]
C-backspace = "delete_word_backward"

# Windows-like movement (again)
C-left = [ "move_prev_word_start", "move_char_left", "move_char_right" ]
C-right = [ "move_next_word_start", "move_char_left", "move_char_right" ]
